### ISSUE TITLE
Port SDF-2-SDF 2D C++ code to python

### ISSUE THREAD

**Issue by Algomorph** [Algomorph/LevelSetFusion-Python#20]
Should be done compatible with the existing code structure of the C++ module.

Make new rigid_alignment.cpp and rigid_alignment.hpp files in the src/python-export folder. Use the python_export namespace. Utilize resulting functions in src/module.cpp

Work should be done in a separate branch feature/sdf2sdf of the LevelSetFusion-CPP repository.

**Comment by Algomorph** [comment]
@fshanAtUMD , please give me a time estimate for completing this.

**Comment by fei-shan** [comment]
I'm finishing c++ 2D implementation by Mar 8.

**Comment by Algomorph** [comment]
@fshanAtUMD Thank you! A friendly reminder: please move this to the "In Progress" column in the project management. You are responsible for managing your issues and making sure they stay up-to-date on the Project board.

**Comment by fei-shan** [comment]
Thanks for reminding, I moved them respectively.
