### ISSUE TITLE
Write unit tests for python 2D SDF-2-SDF rigid alignment simulation

### ISSUE THREAD

**Issue by Algomorph** [Algomorph/LevelSetFusion-Python#23]
Use existing Python code structure. You already have a test python module in the tests folder, starting with the "test_" prefix. This is good. Make sure name of file and names of tests are descriptive.

Aside: I'm currently investigating on how to use pytest fixtures properly in PyCharm. I might go back and change the way I currently use test data. For now, no need to worry about it much -- make a file like hnso_fixtures if you have large test data matrices.

**Comment by Algomorph** [comment]
Fei, where are you on this issue?

**Comment by fei-shan** [comment]
Half way on it,  writing unit tests. Should be finished in this week. I was working on other assignments earlier this week...

**Comment by Algomorph** [comment]
@fshanAtUMD ok, sounds good, thanks!
