### ISSUE TITLE
Demonstrate how well the rigid alignment works using 2D visualization

### ISSUE THREAD

**Issue by Algomorph** [Algomorph/LevelSetFusion-Python#3]
We need to be able to see how well the target (live) SDF fits the source (canonical) SDF. For this, we need a new "run_sdf2sdf_fusion.py" script, which performs the rigid alignment procedure on two arbitrary depth frames of data (using a specific pixel row for the 2D case), and uses utils/visualization.py & opencv ffmpeg-based encoder for the data.

**Comment by Algomorph** [comment]
Needs to be reviewed by Matthias

**Comment by Algomorph** [comment]
@fshanAtUMD Was Matthias satisfied with the optimization result? Can this issue be closed?

**Comment by fei-shan** [comment]
I talked to professor after class today and he thinks it's good, and confirmed that I can move on to the next step.

**Comment by Algomorph** [comment]
@fshanAtUMD Thanks, this can now be closed.
